// Code generated by protoc-gen-go. DO NOT EDIT.
// source: a.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sex int32

const (
	Sex_NO    Sex = 0
	Sex_MAN   Sex = 1
	Sex_WOMAN Sex = 2
)

var Sex_name = map[int32]string{
	0: "NO",
	1: "MAN",
	2: "WOMAN",
}

var Sex_value = map[string]int32{
	"NO":    0,
	"MAN":   1,
	"WOMAN": 2,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}

func (Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44591ff926c61195, []int{0}
}

type Send struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Hobby                []string `protobuf:"bytes,3,rep,name=hobby,proto3" json:"hobby,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send) Reset()         { *m = Send{} }
func (m *Send) String() string { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()    {}
func (*Send) Descriptor() ([]byte, []int) {
	return fileDescriptor_44591ff926c61195, []int{0}
}

func (m *Send) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send.Unmarshal(m, b)
}
func (m *Send) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send.Marshal(b, m, deterministic)
}
func (m *Send) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send.Merge(m, src)
}
func (m *Send) XXX_Size() int {
	return xxx_messageInfo_Send.Size(m)
}
func (m *Send) XXX_DiscardUnknown() {
	xxx_messageInfo_Send.DiscardUnknown(m)
}

var xxx_messageInfo_Send proto.InternalMessageInfo

func (m *Send) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Send) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Send) GetHobby() []string {
	if m != nil {
		return m.Hobby
	}
	return nil
}

type Say struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Sex                  Sex      `protobuf:"varint,2,opt,name=sex,proto3,enum=proto.Sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Say) Reset()         { *m = Say{} }
func (m *Say) String() string { return proto.CompactTextString(m) }
func (*Say) ProtoMessage()    {}
func (*Say) Descriptor() ([]byte, []int) {
	return fileDescriptor_44591ff926c61195, []int{1}
}

func (m *Say) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Say.Unmarshal(m, b)
}
func (m *Say) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Say.Marshal(b, m, deterministic)
}
func (m *Say) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Say.Merge(m, src)
}
func (m *Say) XXX_Size() int {
	return xxx_messageInfo_Say.Size(m)
}
func (m *Say) XXX_DiscardUnknown() {
	xxx_messageInfo_Say.DiscardUnknown(m)
}

var xxx_messageInfo_Say proto.InternalMessageInfo

func (m *Say) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Say) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_NO
}

func init() {
	proto.RegisterEnum("proto.Sex", Sex_name, Sex_value)
	proto.RegisterType((*Send)(nil), "proto.Send")
	proto.RegisterType((*Say)(nil), "proto.Say")
}

func init() { proto.RegisterFile("a.proto", fileDescriptor_44591ff926c61195) }

var fileDescriptor_44591ff926c61195 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8d, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0x87, 0x2f, 0xcd, 0xa5, 0x67, 0x9f, 0x28, 0xe5, 0x21, 0x52, 0xc4, 0xa1, 0x16, 0x84, 0xe2,
	0x70, 0xc3, 0x09, 0x2e, 0x4e, 0x3a, 0xb9, 0x78, 0x27, 0xc9, 0xe0, 0x9c, 0xd8, 0x87, 0x0a, 0x6d,
	0x22, 0xa9, 0x4a, 0xf3, 0xdf, 0x1f, 0x4d, 0x4b, 0xa7, 0xf7, 0x7d, 0x6f, 0xf8, 0x7e, 0xb0, 0xd1,
	0xdb, 0x1f, 0xef, 0x7e, 0x1d, 0x8a, 0x78, 0xaa, 0x67, 0x58, 0x2b, 0xb2, 0x0d, 0x22, 0xac, 0xad,
	0xee, 0xa8, 0x60, 0x25, 0xab, 0x33, 0x19, 0x19, 0x73, 0xe0, 0xfa, 0x93, 0x8a, 0xa4, 0x64, 0xb5,
	0x90, 0x23, 0xe2, 0x05, 0x88, 0x2f, 0x67, 0x4c, 0x28, 0x78, 0xc9, 0xeb, 0x4c, 0x4e, 0x52, 0x3d,
	0x02, 0x57, 0x3a, 0xe0, 0x25, 0xa4, 0xf6, 0xaf, 0x33, 0xe4, 0xe7, 0xc8, 0x6c, 0x78, 0x0d, 0xbc,
	0xa7, 0x21, 0x66, 0xce, 0x77, 0x30, 0xcd, 0x6f, 0x15, 0x0d, 0x72, 0x7c, 0xdf, 0xdd, 0x00, 0x57,
	0x34, 0x60, 0x0a, 0xc9, 0xfe, 0x90, 0xaf, 0x70, 0x03, 0xfc, 0xf5, 0x69, 0x9f, 0x33, 0xcc, 0x40,
	0xbc, 0x1f, 0x46, 0x4c, 0x76, 0x0f, 0x70, 0xf6, 0x46, 0xbe, 0x77, 0x56, 0x91, 0xff, 0xff, 0xfe,
	0x20, 0xbc, 0x85, 0x13, 0xa5, 0xc3, 0x0b, 0xb5, 0xad, 0xc3, 0xd3, 0x25, 0x68, 0x9b, 0xab, 0xa5,
	0xae, 0x43, 0xb5, 0x32, 0x69, 0x94, 0xfb, 0x63, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x25, 0x4d,
	0x5c, 0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	SayHello(ctx context.Context, in *Send, opts ...grpc.CallOption) (*Say, error)
}

type personServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonServiceClient(cc grpc.ClientConnInterface) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) SayHello(ctx context.Context, in *Send, opts ...grpc.CallOption) (*Say, error) {
	out := new(Say)
	err := c.cc.Invoke(ctx, "/proto.PersonService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	SayHello(context.Context, *Send) (*Say, error)
}

// UnimplementedPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServiceServer struct {
}

func (*UnimplementedPersonServiceServer) SayHello(ctx context.Context, req *Send) (*Say, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Send)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersonService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).SayHello(ctx, req.(*Send))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _PersonService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
